config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'

  get 'sell'    => 'static_pages#sell'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms'   => 'static_pages#terms' 

  get 'signup'  => 'users#new'
  get 'register' => 'booths#new'
  get '/categories/:id' =>'categories#show'

  get "search" => "search#index"

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :booths
  resources :items
  resources :relationships, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  @items = Item.all
end

  def sell 
  end

  def help
  end

  def about
  end

  def terms
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h2 class="text-center">About</h2>
<p>info coming soon
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h2 class="text-center">Contact</h2>
<p> info coming soon
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h2 class="text-center">Help</h2>
<p> info coming soon
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<div class="container-fluid">
    	<h1>Welcome to Sewingly</h1>
    	<p>A community marketplace for knitters, sewists, and other needle artists.</p>
  	</div>
</div>

	<div class="container">
  		<h2 class ="text-center">Homespun Finds</h2>
  		<p class="text-center">Discover unique items from the knitter, the quilter, and the .</p>
	</div>

<div class="container-fluid">
	<div class="row">
    	<%= render @items %>
  	</div>
</div>

<div class="jumbotron jumbotron-two">
  <div class="container-fluid">
      <h2>Fabrics, trims, and threads...</h2>
      <p>Find beautiful supplies from specialty shops and artists' closets. </p>
      
    </div>
</div>

app/views/static_pages/sell.html.erb
<% provide(:title, "Sell") %>

<h2 class="text-center">What can you sell on sewingly?</h2>

<div class="container">
  <div class="row">
   <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
         <a href="#"><img src="https://img1.etsystatic.com/043/0/8674457/il_570xN.640818797_e8rr.jpg" 
         alt="Generic placeholder thumbnail"></a>
      </div>
      <div class="caption">
        <p>craft supplies from specialty shops or leftover supplies from your last project.</p>
          
      </div>
   </div>

   <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
         <a href="#"><img src="https://img1.etsystatic.com/032/0/9803418/il_570xN.645202375_1y0w.jpg" 
         alt="Generic placeholder thumbnail"></a>
      </div>
      <div class="caption">
        <p>homespun items.  knitting, weaving, sewing, etc.  </p>
          
      </div>
   </div>

   <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
         <a href="#"><img src="http://media-cache-ec0.pinimg.com/736x/17/e2/00/17e20059e6b6d77789b5efc41f722513.jpg" 
         alt="Generic placeholder thumbnail"></a>
      </div>
      <div class="caption">
        <p>items made by you, your club, or your collective, but absolutely nothing outsourced to a factory.</p>
          
      </div>
    </div>
  </div>
</div>

  <% if logged_in? %>

    <%= link_to "open a booth on sewingly", register_path, class: "btn btn-primary col-md-4 col-md-offset-4" %>

  <% else %>

    <%= link_to "login to open booth", login_path, class: "btn btn-primary col-md-4 col-md-offset-4" %>

  <% end %>




  
   

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms") %>
<h2 class="text-center">Terms</h2>
<p>
  info coming soon
</p>