config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'

  get 'sell'    => 'static_pages#sell'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms'   => 'static_pages#terms' 

  get 'signup'  => 'users#new'
  get 'register' => 'booths#new'
  get '/categories/:id' =>'categories#show'

  get "search" => "search#index"

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :booths
  resources :items
  resources :relationships, only: [:create, :destroy]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user 
  belongs_to :category 
  default_scope -> { order('created_at DESC') }
  

  mount_uploader :image, ImageUploader
  mount_uploader :image_two, ImageTwoUploader

  validates :user_id, presence: true
  validates :name, presence: true, length: {minimum: 3, maximum: 100}
  validates :description, presence: true, length: {minimum: 10}
  validates :price, presence: true, numericality: true
  validates :image, presence: true
  validate  :image_size

  # Validates the size of an uploaded picture.
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	before_action :logged_in_user, only: [:edit, :update, :new, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

	def index
  	@items = Item.where.not(category_id: 1)
	end

	def new
 		@item = Item.new
  	end

  def create
  @item = current_user.items.build(item_params)
    if @item.save
    flash[:success] = "Item successfully added to booth"
    redirect_to root_url
  else
    render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end 

  def update
  @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = "item changes saved"
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    flash[:success] = "Item deleted"
    redirect_to root_url
  end


	def show
		@item = Item.find(params[:id])
  end

	private

  def item_params
    params.require(:item).permit(:name, :price, :description, :image, :image_two, :category_id,)
  end


  
  def correct_user
    @item = Item.find(params[:id])
    redirect_to(root_url) unless current_user == @item.user
  end
end

app/helpers/items_helper.rb
module ItemsHelper	
end

app/views/items/_item.html.erb
<div class="col-md-3 item">
  
  <div class="thumbnail">
		  <%= link_to item_path(item) do %>
  		<%= image_tag(item.image.url(:thumb)) %>
		  <% end %>
	</div>
     	
  <div class="caption">
    <span id="item-maker-partial"> 
      <%= link_to item_path(item) do %>
      <%= item.name %>
      <% end %>
    </span>
      	
    <span class="pull-right" id="item-price-partial"> 
      <%= link_to item_path(item) do %>
      <%= number_to_currency item.price %>
      <% end %>
    </span>
  </div>
</div>

 

  


  

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<h3 class="text-center">edit item</h3>


<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@item, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>


      <%= f.label :name, "item name" %>
      <%= f.text_field :name, class: 'form-control' %>

      
      <%= f.label :category_id, "choose category" %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, {class: "form-control"} %>

      <%= f.label :price, "price" %>
      <%= f.text_field :price, class: 'form-control' %>

      <%= f.label :description, "item description" %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :image, "image one" %>
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'upload' %>

      <%= f.label :image_two, "image two" %>
      <%= f.file_field :image_two, accept: 'image/jpeg,image/gif,image/png', class: 'upload' %>

      <%= f.submit "save changes", class: "btn btn-primary" %>


    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#item_image').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum image size is 5MB. Please choose a smaller image.');
    }
  });
</script>

app/views/items/index.html.erb
<% provide(:title, 'Items') %>

<h2 class ="text-center"> Homespun Items </h2>
<p class ="text-center">Browse items made by our community of fabric and needle artists.</p>

<div class="container-fluid">
  <div class="row">
    <%= render @items %>
  </div>
</div>

app/views/items/new.html.erb
<% provide(:title, 'Add Item') %>
<h2 class="text-center">add item to your booth</h2>


<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@item, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>


      <%= f.label :name, "item name" %>
      <%= f.text_field :name, class: 'form-control' %>

      
      <%= f.label :category_id, "choose category" %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, {class: "form-control"} %>

      <%= f.label :price, "price" %>
      <%= f.text_field :price, class: 'form-control' %>

      <%= f.label :description, "item description" %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :image, "image one" %>
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'upload' %>

      <%= f.label :image_two, "image two" %>
      <%= f.file_field :image_two, accept: 'image/jpeg,image/gif,image/png', class: 'upload' %>

      <%= f.submit "add item", class: "btn btn-primary" %>


    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#item_image').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum image size is 5MB. Please choose a smaller image.');
    }
  });
</script>
  

  

app/views/items/show.html.erb
<% provide(:title, "Item Details") %>

<div class="container item-page-container">
	<div class = "row">
		
    <div class="col-md-6">
      <div class= "thumbnail">
      		<%= image_tag @item.image_url() if @item.image? %>
          <br></br>
          <%= image_tag @item.image_two_url() if @item.image_two? %>
          <br></br>
      </div>
    </div>

    <div class="col-md-6">
		  <h3><%= @item.name %></h3>
		  
      <h4><%= number_to_currency @item.price %> </h4>
      
      <p><%= @item.description %></p>
       
       <p>by<%= link_to @item.user do %>
       <%= @item.user.name %>
       <% end %> </p>
      

      <p>from booth <%= link_to @item.user.booth do %> 
        <%= @item.user.booth.name %>
        <% end %> </p>
		  
		  <% if current_user?(@item.user) %>
      <%= link_to "delete", @item, class: "btn", method: :delete,
                                       data: { confirm: "What?! Are you sure?" } %>
      <%= link_to "edit", edit_item_path, class: "btn" %>
      <% elsif %>
                                         
                                         
    
      <%= link_to "Buy Now with PayPal", '#', class: "btn btn-primary col-md-8", id: "paypal-buy-btn"%>
      <% end %>

      <!-- Disqus Integraton -->

         <div id="disqus_thread"></div>
            <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'sewingly'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
            </script>
          <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>
  </div>
</div>

      

      








	