config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'

  get 'sell'    => 'static_pages#sell'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms'   => 'static_pages#terms' 

  get 'signup'  => 'users#new'
  get 'register' => 'booths#new'
  get '/categories/:id' =>'categories#show'

  get "search" => "search#index"

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :booths
  resources :items
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      <p> &#169;sewingly 2015</p>
    </small>
    <nav>
      <ul>
         <li><a href="https://www.facebook.com/sewingly">Facebook</a></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Terms", terms_path%> </li>
       </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "Sewingly", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-left">
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              browse <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><%= link_to "Craft Supplies", '/categories/1' %></li>
            <li><%= link_to "Homespun Items", items_path %></li>
        </ul>
          </li>
      </ul>


      <ul class = "nav navbar-nav pull-left">
        <li><%= link_to "Community Threads", '#' %></li>
        <li class="navbar-search" >
        <%= form_tag search_path, method: :get do %>
        <%= search_field_tag :q, '', class: "search-query", placeholder: "search sewingly" %>
        <span class="glyphicon glyphicon-search"></span>
        
        <% end %> </li>
      </ul>


    <% if logged_in? && has_booth?(current_user.id) %>
    
      <ul class = "nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle= "dropdown">Booth <b class ="caret"> </b> </a>
      <ul class="dropdown-menu pull-right">
        <li><%= link_to "Add New Item", new_item_path %></li>
        <li><%= link_to "Visit Your Booth", current_user.booth %></li> 
        <li><%= link_to "Booth Settings", edit_booth_path(current_user.booth) %></li>
      </ul>
    </li>

    <ul class = "nav navbar-nav pull-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b></a>
    
    <ul class="dropdown-menu pull-right">
        <li><%= link_to "View Profile", current_user %></li>
        <li><%= link_to "Update Settings", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
    </ul>
      </li>
  </ul>

         

<% elsif logged_in? && !has_booth?(current_user.id) %>
  <ul class = "nav navbar-nav pull-right">
    <li><%=link_to "Sell Goods", sell_path %></li>
    <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b></a>

      <ul class="dropdown-menu pull-right">

        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
    </li>
  </ul>

<% else %>
    <ul class="nav navbar-nav pull-right">
      <li><%=link_to "Sell Goods", sell_path %></li>
      <li><%= link_to "Sign Up", signup_path %></li>
      <li><%= link_to "Log in", login_path %></li>
    </ul>
<% end %>
    </nav>
  </div>
</header>






  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>

      <%= yield %>
       <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>

    
  </body>
</html>